on: [push]

jobs:
  test_job:
    runs-on: ubuntu-18.04
    name: Run Crashers Test
    steps:
    - uses: actions/checkout@v1
    - name: Test on armv7
      uses: uraimo/run-on-arch-action@v1.0.5
      with:
        architecture: armv6
        distribution: buster
        run: |
          apt update
          apt install -y libatomic1 libbsd0 clang libicu-dev libcurl4-nss-dev
          apt install -y curl git
          curl -OkL https://github.com/uraimo/buildSwiftOnARM/releases/download/5.1/swift-5.1-armv6-RPi01234-RaspbianBuster.tgz
          tar xzf swift-5.1-armv6-RPi01234-RaspbianBuster.tgz
          cd Crashers
          ../usr/bin/swift test
